name: generate list

on:
  push:
    branches:
      - main  # 或者指定您仓库的默认分支

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate list.txt
        run: |
          # 确保 ./problems 目录存在
          if [ -d ./problems ]; then
            # 查找子目录并写入 list.txt
            find ./problems -mindepth 1 -maxdepth 1 -type d -exec basename {} \; > ./problems/list.txt
          else
            echo "No problems directory found" > ./problems/list.txt
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./problems/list.txt
          git commit -m "Update list.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
